stages:
  - build
  - deploy
  - build-prod
  - deploy-prod
Build:
  stage: build
  needs: []
  image: docker:20.10.9
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo -e "$DEV_ENV" > .env
  script:
    - docker system  prune -a -f
    - docker build --pull -t git.bts-co.com:5050/root/bts-front-app:dev .
    - docker push git.bts-co.com:5050/root/bts-front-app:dev
  only:
    - main
  tags:
    - build-runner2

deploy:
  stage: deploy
  environment:
    name: development
  # image: docker:20.10.9
  needs: [Build]
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker image prune -f
    - docker pull git.bts-co.com:5050/root/bts-front-app:dev
    - docker service update --force --image git.bts-co.com:5050/root/bts-front-app:dev bts_Ui-dev --with-registry-auth
    
  only:
    - main
  tags:
    - dev-server-deployment


Build-prod:
  stage: build-prod
  environment:
    name: production
  needs: []
  image: docker:20.10.9
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo -e "$PROD_ENV" > .env
  script:
    - docker system  prune -a -f
    - docker build --pull -t git.bts-co.com:5050/root/bts-front-app:prod .
    - docker push git.bts-co.com:5050/root/bts-front-app:prod
  only:
    - tags
  tags:
    - build-runner2

deploy-prod:
  stage: deploy-prod
  environment:
    name: production
  # image: docker:20.10.9
  needs: [Build-prod]
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker image prune -f
    - docker pull git.bts-co.com:5050/root/bts-front-app:prod
    - docker service update --force --image git.bts-co.com:5050/root/bts-front-app:prod bts_Ui-prod --with-registry-auth
    
  only:
    - tags
  tags:
    - prod-server-deployment


