stages:
  - build
  - deploy
  - build-prod
  - deploy-prod
Build:
  stage: build
  needs: []
  image: docker:20.10.9
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
    - echo -e "$DEV_ENV" > .env
  script:
    - docker system  prune --filter="label!=keep-cache" -f
    - docker build -t $REGISTRY/bts/bts-front-app:dev .
    # - docker build --pull -t $REGISTRY/bts/bts-front-app:dev .
    - docker push $REGISTRY/bts/bts-front-app:dev
  only:
    - main
  tags:
    - bts-runner1

deploy:
  stage: deploy
  environment:
    name: development
  # image: docker:20.10.9
  needs: [Build]
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
  script:
    - docker image prune -f
    - docker pull $REGISTRY/bts/bts-front-app:dev
    - docker service update --force --image $REGISTRY/bts/bts-front-app:dev bts_Ui-dev --with-registry-auth
    
  only:
    - main
  tags:
    - bts-dev-deploy


Build-prod:
  stage: build-prod
  environment:
    name: production
  needs: []
  image: docker:20.10.9
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
    - echo -e "$PROD_ENV" > .env
  script:
    - docker system  prune --filter="label!=keep-cache" -f
    - docker build --pull -t $REGISTRY/bts/bts-front-app:${CI_COMMIT_TAG} .
    - docker push $REGISTRY/bts/bts-front-app:${CI_COMMIT_TAG}
  only:
    - tags
  tags:
    - bts-runner1

deploy-prod:
  stage: deploy-prod
  environment:
    name: production
  # image: docker:20.10.9
  needs: [Build-prod]
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
  script:
    - docker image prune -f
    - docker pull $REGISTRY/bts/bts-front-app:${CI_COMMIT_TAG}
    - docker service update --force --image $REGISTRY/bts/bts-front-app:${CI_COMMIT_TAG} bts_Ui-prod --with-registry-auth
    
  only:
    - tags
  tags:
    - bts-prod-deploy


