services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_CHAT_URL=ws://82.115.25.219:8000/ws
      - REACT_APP_API_BASE_URL=http://82.115.25.219:8000
